# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
 
  lane :beta do
    increment_build_number
    build_app(scheme: "HelloWorld", export_xcargs: "-allowProvisioningUpdates")
    upload_to_testflight
  end
end

lane :release do
  increment_build_number
  capture_screenshots                  # generate new screenshots for the App Store
  sync_code_signing(type: "appstore")  # see code signing guide for more information
  build_app(scheme: "HelloWorld")
  upload_to_app_store                  # upload your app to App Store Connect
end